### ISSUE TITLE
[solved] Dependency Error for jekyll-figure 

### ISSUE THREAD

**Issue by bsde1245** [lordamit/jekyll-instant-article-facebook#2]
Hi @LordAmit When I run bundle exec jekyll serve I get following error message
```
 Dependency Error: Yikes! It looks like you don't have jekyll-figure or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- jekyll-figure' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/! 
jekyll 3.4.0 | Error:  jekyll-figure
```
I added gem to gemfile and did a bundle install ...Still got error message
Any way to fix this, Thanks.

**Comment by LordAmit** [comment]
Hello @justinechacko ,
You need to install the jekyll-figure gem 😄 

Here are the details:
https://github.com/paulrobertlloyd/jekyll-figure

**Comment by bsde1245** [comment]
I tried. I got the above error

**Comment by LordAmit** [comment]
Ah, can you share your gemfile?

**Comment by bsde1245** [comment]
http://talk.jekyllrb.com/t/dependency-error-jekyll-figure/

**Comment by bsde1245** [comment]
Hi @LordAmit 
Here is the gemfile

```
source "https://rubygems.org"
ruby RUBY_VERSION

# This will help ensure the proper Jekyll version is running.
gem "jekyll", "3.4.0"
gem 'jekyll-paginate'
gem 'jekyll-sitemap'
gem 'jekyll-figure'


# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

```

Did a bundle install and it installed jekyll figure plugin...

config file

```
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Name
email: contact@domainname.com
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

twitter_username: 
github_username:  
owner:
  name:           Name
  avatar:         images/Your_image.jpg
# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
    load_paths:
        - _sass
        - bs
paginate: 10
paginate_path: "page:num"
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-figure
```
